name: test
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: root directory
      run: |
        Get-ChildItem C:\
    - uses: conda-incubator/setup-miniconda@v1
      with:
        miniconda-version: "latest"
        activate-environment: mkl
    - name: install stuff
      run: |
        conda install -y mkl mkl-include mkl-devel
        Get-ChildItem -Recurse C:\Miniconda3\envs\mkl\Library
    # - uses: actions/checkout@v2
    - name: checkout itensor-cmake
      run: |
        pwd
        git clone https://github.com/kyungminlee/itensor-cmake.git
        cd itensor-cmake
        git submodule update --init
    - name: show
      run: |
        pwd
        dir
    - name: build
      run: |
        cd itensor-cmake
        cmake -B build -DBLA_VENDOR=Intel10_64_dyn -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\installdir"
        cmake --build build
      env:
        LAPACK_INCLUDE_DIR: C:\Miniconda3\envs\mkl\Library\include
        MKLROOT: C:\Miniconda3\envs\mkl\Library