name: test
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Add Miniconda to PATH
      run: |
        echo "C:\Miniconda" >> $Env:GITHUB_PATH
        echo "C:\Miniconda\condabin" >> $Env:GITHUB_PATH
        echo "C:\Miniconda\Library\bin" >> $Env:GITHUB_PATH
    - name: install stuff
      run: |
        conda install -y mkl mkl-include mkl-devel
    - name: checkout itensor-cmake
      run: |
        git clone https://github.com/kyungminlee/itensor-cmake.git
        cd itensor-cmake
        git submodule update --init
    - name: build
      run: |
        cd itensor-cmake
        cmake -B build -DBLA_VENDOR=Intel10_64_dyn -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\installdir"
        cmake --build build --config Release --target install
      env:
        LAPACK_INCLUDE_DIR: C:\Miniconda\Library\include
        MKLROOT: C:\Miniconda\Library
    - name: compress
      run: |
        7z a ${{ github.workspace }}\foo.zip ${{ github.workspace }}\installdir
    - uses: actions/upload-artifact@v2
      with:
        name: foo.zip
        path: ${{ github.workspace }}/foo.zip